"""Regenerate docs/automation-catalog.md from skill and agent metadata."""

import sys
from pathlib import Path
from typing import Any

import yaml
import typer
from rich.console import Console

# Rich uses Unicode glyphs (✓) — force UTF-8 stdout so cp1252 Windows shells don't crash.
if hasattr(sys.stdout, "reconfigure"):
    sys.stdout.reconfigure(encoding="utf-8")

app = typer.Typer()
console = Console()

REPO_ROOT = Path(__file__).parent.parent.parent
SKILLS_DIR = REPO_ROOT / ".claude" / "skills"
AGENTS_DIR = REPO_ROOT / ".claude" / "agents"
GITHUB_SKILLS_DIR = REPO_ROOT / ".github" / "skills"
OUTPUT = REPO_ROOT / "docs" / "automation-catalog.md"

DOMAIN_ORDER = ["ado", "office", "comms", "devops", "coding", "data-ml", "infra", "docs", "meta"]
DOMAIN_LABELS = {
    "ado": "ADO",
    "office": "Office / Non-tech Outputs",
    "comms": "Communication",
    "devops": "DevOps / CI-CD",
    "coding": "Coding / SCM",
    "data-ml": "Data / ML",
    "infra": "Platform / Infra",
    "docs": "Documentation",
    "meta": "Repo Self-Maintenance (Meta)",
}


def parse_frontmatter(path: Path) -> dict[str, Any]:
    text = path.read_text(encoding="utf-8")
    if not text.startswith("---"):
        return {}
    try:
        end = text.index("---", 3)
        return yaml.safe_load(text[3:end]) or {}
    except (ValueError, yaml.YAMLError):
        return {}


def collect_skills() -> dict[str, list[dict]]:
    by_domain: dict[str, list[dict]] = {}
    for skill_md in SKILLS_DIR.rglob("SKILL.md"):
        fm = parse_frontmatter(skill_md)
        if not fm.get("name"):
            continue
        domain = fm.get("domain", "meta")
        by_domain.setdefault(domain, []).append({
            "name": fm["name"],
            "description": fm.get("description", ""),
            "script": fm.get("script", ""),
            "requires_script": fm.get("requires_script", False),
        })
    for domain in by_domain:
        by_domain[domain].sort(key=lambda x: x["name"])
    return by_domain


def collect_agents() -> list[dict]:
    agents = []
    for agent_md in sorted(AGENTS_DIR.glob("*.agent.md")):
        fm = parse_frontmatter(agent_md)
        if fm.get("name"):
            agents.append({"name": fm["name"], "description": fm.get("description", "")})
    return agents


def collect_github_skills() -> list[dict]:
    if not GITHUB_SKILLS_DIR.exists():
        return []
    skills = []
    for skill_md in sorted(GITHUB_SKILLS_DIR.glob("*/SKILL.md")):
        fm = parse_frontmatter(skill_md)
        if not fm.get("name"):
            continue
        skills.append({
            "name": fm["name"],
            "description": fm.get("description", ""),
            "mode": fm.get("mode", ""),
        })
    return skills


def render_catalog(skills: dict, agents: list, github_skills: list) -> str:
    lines = [
        "# Automation Catalog",
        "",
        "> Auto-generated by `scripts/repo/generate_catalog.py`. "
        "Run it after adding new skills to keep this up to date.",
        "",
        "---",
        "",
        "## Claude Code Skills",
        "",
        "Invoke any skill by typing `/<skill-name>` in Claude Code chat.",
        "",
    ]

    for domain in DOMAIN_ORDER:
        if domain not in skills:
            continue
        label = DOMAIN_LABELS.get(domain, domain)
        lines += [f"### {label}", ""]
        lines += ["| Skill | Description | Script |", "|---|---|---|"]
        for s in skills[domain]:
            script_cell = f"`{s['script']}`" if s.get("script") else "—"
            lines.append(f"| `/{s['name']}` | {s['description']} | {script_cell} |")
        lines.append("")

    # Any domains not in DOMAIN_ORDER
    for domain, items in skills.items():
        if domain in DOMAIN_ORDER:
            continue
        lines += [f"### {domain}", ""]
        lines += ["| Skill | Description | Script |", "|---|---|---|"]
        for s in items:
            script_cell = f"`{s['script']}`" if s.get("script") else "—"
            lines.append(f"| `/{s['name']}` | {s['description']} | {script_cell} |")
        lines.append("")

    lines += [
        "---",
        "",
        "## Claude Code Agents",
        "",
        "Agents are persistent modes. Select one from the agent list in Claude Code.",
        "",
        "| Agent | Description |",
        "|---|---|",
    ]
    for a in agents:
        lines.append(f"| `{a['name']}` | {a['description']} |")

    lines += [
        "",
        "---",
        "",
        "## GitHub Copilot Skills",
        "",
        "Use in Copilot Chat: type `/` and select a skill, or reference by name in agent sessions.",
        "",
        "| Skill | Mode | Description |",
        "|---|---|---|",
    ]
    for s in github_skills:
        mode_cell = f"`{s['mode']}`" if s.get("mode") else "—"
        lines.append(f"| `/{s['name']}` | {mode_cell} | {s['description']} |")

    lines.append("")
    return "\n".join(lines)


@app.command()
def main() -> None:
    console.print("Scanning skills, agents, and GitHub skills...")
    skills = collect_skills()
    agents = collect_agents()
    github_skills = collect_github_skills()

    skill_count = sum(len(v) for v in skills.values())
    console.print(f"  Found {skill_count} skills across {len(skills)} domains")
    console.print(f"  Found {len(agents)} agents")
    console.print(f"  Found {len(github_skills)} GitHub Copilot skills")

    catalog = render_catalog(skills, agents, github_skills)
    OUTPUT.write_text(catalog, encoding="utf-8")
    console.print(f"[green]✓ Written: {OUTPUT.relative_to(REPO_ROOT)}[/green]")


if __name__ == "__main__":
    app()
